### PR TITLE
Added `FilterEdges` graph coarsening operator

### PR DESCRIPTION
**Pull request by wsad1**

### CODE REVIEW

**Comment by puririshi98** [comment]
LGTM besides dropping the old filter_adj function: https://github.com/pyg-team/pytorch_geometric/pull/7361/files#diff-eeda03d73110e079fdee8218bb69b7021bf6b21158471c6d07edb9a41c40f934R11

**Comment by wsad1** [comment]
@puririshi98 any reason you want to keep the old `filter_adj` function. Is it used in other places?

**Comment by puririshi98** [comment]
> @puririshi98 any reason you want to keep the old `filter_adj` function. Is it used in other places?

no reason, in my previous comment I mentioned
`LGTM besides dropping the old filter_adj function: https://github.com/pyg-team/pytorch_geometric/pull/7361/files#diff-eeda03d73110e079fdee8218bb69b7021bf6b21158471c6d07edb9a41c40f934R11`

**Comment by puririshi98** [comment]
turns out its needed for pan pool: https://github.com/pyg-team/pytorch_geometric/actions/runs/5258060418/jobs/9501770183?pr=7361
will fix

**Comment by wsad1** [comment]
@puririshi98 feel free to approve it if you feel its ready. We can merge after that.

**Review by puririshi98 — APPROVED** [review]

**Pull request merged**
