### PR TITLE
feat: migrate to `pyproject.toml` for building package

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
Changes proposed by this PR can be summarized as follows :-

* Delete `setup.py` in favour of `pyproject.toml` for packaging.
* Update `pre-commit` configuration with an updated version of `pyroma` to check packaging quality of `pyproject.toml`.
* Update workflows to build using `python -m build`.

---

`pyproject.toml` is the new standard for packaging python packages, `setup.py` is now deprecated (first introduced in [PEP 518](https://peps.python.org/pep-0518/) and later expanded in [PEP 517](https://peps.python.org/pep-0517/), [PEP 621](https://peps.python.org/pep-0621/) and [PEP 660](https://peps.python.org/pep-0660/)).

### CODE REVIEW

**Comment by SauravMaheshkar** [comment]
@rusty1s, the pre-commit checks are passing on my machine with the updated version of `pyroma`. Not sure why it is failing in CI.

**Comment by SauravMaheshkar** [comment]
@rusty1s I think the `pre-commit` CI is failing because it picks up the configuration from the `master` branch and not the branch the PR is from. I think you'll be able to verify that `pre-commit` passes by running it on my branch using the updated `pre-commit` configuration with the newer version of `pyroma` (the version that supports PEP 517).

**Comment by rusty1s** [comment]
Got it. Will try to get this in as part of our PyG 2.3 release.

**Comment by SauravMaheshkar** [comment]
@rusty1s do you think this will get into the release (hopefully) happening on March 21 👀

**Comment by SauravMaheshkar** [comment]
Seems like there is a conflict in `setup.py` because of the version bump.

**Comment by SauravMaheshkar** [comment]
@rusty1s can you fix this merge conflict ? I'm not sure if simply bumping the version in `setup.py` would help.

**Review by rusty1s — APPROVED** [review]

**Comment by SauravMaheshkar** [comment]
Interesting, it's taking forever to finish.

**Pull request merged**
