### PR TITLE
Fixed `BasicGNN` for `num_layers=1` and `out_channels` given

### PR DESCRIPTION
**Pull request by fjulian**
If a model based on `nn.BasicGNN` is created with a single layer and `out_channels` given, the existing code added two layers, where the last layer is a convolution bringing the channel size to `out_channels`. However, this second layer was never reached since in `forward`, the `for` loop only iterates up to `num_layers`. Therefore, the output graph has (counterintuitively) `hidden_channels` channels, instead of `out_channels`.

This PR adds a test for the 1 layer case, which fails with the existing code. Furthermore, the code for `nn.BasicGNN` is extended to properly handle the 1 layer case, making the test pass.

### CODE REVIEW

**Comment by Padarn** [comment]
Interesting, it seems to me that 
```
        out_channels (int, optional): If not set to :obj:`None`, will apply a
            final linear transformation to convert hidden node embeddings to
            output size :obj:`out_channels`. (default: :obj:`None`)
```
is not true - the 'final linear transformation' doesn't exist, it is done via the convolution layer.

Do you think this docstring should be changed?

**Review by rusty1s — APPROVED** [review]
Thank you!

**Comment by rusty1s** [comment]
@Padarn Can you clarify? The final transformation `self.lin` is defined whenever `self.jk is not None`.

**Comment by Padarn** [comment]
From the docstring, I would expect a linear transform even when `jk` is None, as long as `out_channels` is not None.  Not a huge deal of course.

**Comment by rusty1s** [comment]
Yeah, I understand. Ultimately, we wanted to support both options, since some models perform better on some datasets when the final classifier is performed inside the convolution.

**Comment by Padarn** [comment]
Makes sense. I think explaining that in the docstring would be more confusing than what is already there.

**Pull request merged**
