### PR TITLE
Group datasets in documentation according to different categories

### PR DESCRIPTION
**Pull request by EdisonLeeeee**
One of many PRs aimed at grouping datasets in PyG according to different categories., addressing https://github.com/pyg-team/pytorch_geometric/issues/6801.

Part of the rendered page in dataset cheatsheet:
image

image

image

### CODE REVIEW

**Comment by EdisonLeeeee** [comment]
Will that be a better view?
image

**Comment by rusty1s** [comment]
Thanks! I actually like the first view more (which separates node types and edge types), although I feel this might get a bit bloated once we add more heterogeneous graph datasets.

**Comment by EdisonLeeeee** [comment]
Agreed. So let's leave it for now?

**Comment by EdisonLeeeee** [comment]
Update: merged columns `#nodes` and `#edges` to make a compact view.
### Dataset Cheatsheet
image

### DBLP
image

**Review by rusty1s — APPROVED** [review]
Sorry for me taking so long :(

**Comment by LukeLIN-web** [comment]
Awesome, thank you for your great work.

**Pull request merged**
