### PR TITLE
[Documentation] make documentation of `GATConv` and `GATv2Conv` more explicit and accurate

### PR DESCRIPTION
**Pull request by SZiesche**
## What?
I explicitly named the different `\Theta`s used in the different layers by an index s and t (like it is already done in the docs when talking about input sizes). I did the same for a in the GATconv layer. Finally removed the unclear `||` operator and just wrote out the few additions.

## Why?
To solve the issues discussed in https://github.com/pyg-team/pytorch_geometric/issues/8200

## Testing?
No tests needed, as only documentation was changed.

### CODE REVIEW

**Review by EdisonLeeeee — APPROVED** [review]

**Comment by SZiesche** [comment]
ok great, should we make the two failing checks pass? I had a look at the changelog, but the PR doesn't seem to contain something worth mentioning there. The test for previous pytorch version seems not to be failing because of this PR.

How can the stuff be merged in the end?

**Comment by SZiesche** [comment]
hey guys, I wanted to ask again, who can push the merge button (once this is updated with master) and if we need to make the changelog happy.

**Comment by EdisonLeeeee** [comment]
@rusty1s would take care of it :)

**Review by rusty1s — APPROVED** [review]
Thank you, this is indeed much clearer :)

**Comment by SZiesche** [comment]
> Thank you, this is indeed much clearer :)

It was a pleasure. I always like to share such improvements. Documentation is always a difficuilt point, because the author of the code is often hugely biased and has a large knowledge advantage, which makes it pretty hard for him to write the docs.

**Pull request merged**
