### PR TITLE
Improved documentation to help people check their understanding

### PR DESCRIPTION
**Pull request by PabloAMC**
Initial commit of reading group syllabus.

### CODE REVIEW

**Comment by rusty1s** [comment]
This is absolutely great :)
I would love to integrate that directly into our documentation (rather than Jupyter notebooks in the code base). This should increase visibility and ease reviewing. WDYT?

**Comment by PabloAMC** [comment]
> This is absolutely great :) I would love to integrate that directly into our documentation (rather than Jupyter notebooks in the code base). This should increase visibility and ease reviewing. WDYT?

Sure, I can do it. I guess we can add the questions I had added in the Jupyter notebook to the documentation, (to check their understanding). 

What about the reading group itself, how can we organize it? If there is interest I could coordinate. I can create a Google form on this. What do you think @rusty1s? Also, feel free to change the possible readings, if you have something better. I have also thought of explaining how to read csv data and work with heterogeneous graphs, but I am not sure where to put it.

Perhaps we should maintain somewhere a list of things we would like to see added too.

**Comment by rusty1s** [comment]
> Sure, I can do it. I guess we can add the questions I had added in the Jupyter notebook to the documentation, (to check their understanding).

Yes, sounds good :)

> What about the reading group itself, how can we organize it?

I have no particular preference. Please feel free to go ahead with whatever you feel is best. Nonetheless, let's try to first merge this PR and create an issue with things we would like to add. WDYT?

**Comment by PabloAMC** [comment]
I've included the questions in the main documentation. A possible syllabus for reading group might rather be found on https://docs.google.com/document/d/1OWiVCteFLBQ1c7r9EwprB74OQSp7ku_SytBoC84gB00/edit?usp=sharing

**Review by rusty1s — APPROVED** [review]

**Comment by rusty1s** [comment]
This is great. Thanks a lot. I further fixed some styling issues and typos :)

**Pull request merged**
