### PR TITLE
Fixing one of the `captum` tests.

### PR DESCRIPTION
**Pull request by drivanov**
The current PR provides the fix for the following 9 failing tests.
```
FAILED test/explain/algorithm/test_captum_explainer.py::test_captum_explainer_multiclass_classification[index1-ModelTaskLevel.node-MaskType.object-MaskType.attributes-ShapleyValueSampling] - RuntimeError: shape '[-1, 2, 1, 1]' is invalid for input of size 3
FAILED test/explain/algorithm/test_captum_explainer.py::test_captum_explainer_multiclass_classification[index1-ModelTaskLevel.node-MaskType.object-None-ShapleyValueSampling] - RuntimeError: shape '[-1, 2, 1]' is invalid for input of size 3
FAILED test/explain/algorithm/test_captum_explainer.py::test_captum_explainer_multiclass_classification[index1-ModelTaskLevel.node-None-MaskType.attributes-ShapleyValueSampling] - RuntimeError: shape '[-1, 2, 1, 1]' is invalid for input of size 3
FAILED test/explain/algorithm/test_captum_explainer.py::test_captum_explainer_multiclass_classification[index1-ModelTaskLevel.edge-MaskType.object-MaskType.attributes-ShapleyValueSampling] - RuntimeError: shape '[-1, 2, 1, 1]' is invalid for input of size 3
FAILED test/explain/algorithm/test_captum_explainer.py::test_captum_explainer_multiclass_classification[index1-ModelTaskLevel.edge-MaskType.object-None-ShapleyValueSampling] - RuntimeError: shape '[-1, 2, 1]' is invalid for input of size 3
FAILED test/explain/algorithm/test_captum_explainer.py::test_captum_explainer_multiclass_classification[index1-ModelTaskLevel.edge-None-MaskType.attributes-ShapleyValueSampling] - RuntimeError: shape '[-1, 2, 1, 1]' is invalid for input of size 3
FAILED test/explain/algorithm/test_captum_explainer.py::test_captum_explainer_multiclass_classification[index1-ModelTaskLevel.graph-MaskType.object-MaskType.attributes-ShapleyValueSampling] - RuntimeError: shape '[-1, 2, 1, 1]' is invalid for input of size 3
FAILED test/explain/algorithm/test_captum_explainer.py::test_captum_explainer_multiclass_classification[index1-ModelTaskLevel.graph-MaskType.object-None-ShapleyValueSampling] - RuntimeError: shape '[-1, 2, 1]' is invalid for input of size 3
FAILED test/explain/algorithm/test_captum_explainer.py::test_captum_explainer_multiclass_classification[index1-ModelTaskLevel.graph-None-MaskType.attributes-ShapleyValueSampling] - RuntimeError: shape '[-1, 2, 1, 1]' is invalid for input of size 3
```

NOTE: This is a resubmission of [PR#9513](https://github.com/pyg-team/pytorch_geometric/pull/9513), which had some issues with my `captum` branch.

Additional Details Regarding the Fix...
If `method == 'ShapleyValueSampling' and type(index) != int` we do have a situation when tensor `eval_diff` which is calculated [here](https://github.com/pytorch/captum/blob/master/captum/attr/_core/shapley_value.py#L436) has a size of 3. It is impossible to reshape it to  `shape = [-1, 2, 1, 1]` which is calculated [here](https://github.com/pytorch/captum/blob/master/captum/attr/_core/shapley_value.py#L446-L450).
My fix eliminates this specific combination of input parameters from being considered in the `test_captum_explainer_multiclass_classification` test.

### CODE REVIEW

**Comment by rusty1s** [comment]
By my comment in https://github.com/pyg-team/pytorch_geometric/pull/9513, I meant why does our CI is still green even without this fix? I am a bit hesitant to merge this without further understanding.

**Comment by drivanov** [comment]
Our CI is green only because the 187 tests from `L0_unittests` [require](https://github.com/pyg-team/pytorch_geometric/blob/10c4ee43e634bf475a8b3b92b040d7a7d8959a66/test/explain/algorithm/test_captum_explainer.py#L159) the `captum` package to be installed and it is not included in our `PYG` container. This problem shows up when the `pip install captum` command is added to `L0_unittests/test.sh` (see [MR#113](https://gitlab-master.nvidia.com/dl/dgx/pyg/-/merge_requests/113)).

**Comment by puririshi98** [comment]
@akihironitta @rusty1s anything else needed to merge?

**Comment by akihironitta** [comment]
I still have the same question as https://github.com/pyg-team/pytorch_geometric/pull/9549#issuecomment-2257520464. Why do we need to skip the test in such cases? I might be misunderstanding, but I do see the test cases pass in master:

https://github.com/pyg-team/pytorch_geometric/actions/runs/10916480630/job/30297994357

**Comment by drivanov** [comment]
@akihironitta: Thank you for [the link](https://github.com/pyg-team/pytorch_geometric/actions/runs/10916480630/job/30297994357) showing that the `test_captum_explainer.py::test_captum_explainer_multiclass_classification` test passes in the master branch with all combinations of parameters. From the log file, I noticed that your CI is using the `captum` version 0.6.
```
Collecting captum<0.7.0 (from torch-geometric==2.7.0)
  Using cached captum-0.6.0-py3-none-any.whl.metadata (25 kB)
```
In my test, version 0.7 of `captum` (which, I believe is the latest one) was installed by  `pip install captum` command.

Since this test runs correctly in our container when `pip install captum==0.6` is used, I believe you can close the current PR without merging.

**Comment by akihironitta** [comment]
Thanks a lot for confirming this! Since we already set the upper bound at:
https://github.com/pyg-team/pytorch_geometric/blob/642f831db4d785b105683973d857385015fee866/pyproject.toml#L75
I don't think this change is necessary (although it'd be nice to add support for `captum>=0.7.0`, but it's a separate issue).

**Pull request closed without merging**
