### PR TITLE
Fix `fill_value` type in `SortAggregation`

### PR DESCRIPTION
**Pull request by Kh4L**
Fix fill_value type after #7392

### CODE REVIEW

**Comment by Kh4L** [comment]
@rusty1s

**Comment by piotrchmiel** [comment]
Hi team :-) 
Regarding https://github.com/pyg-team/pytorch_geometric/pull/7392. Why does passing a tensor to to_dense_batch causes an issue? I delivered it inside https://github.com/pyg-team/pytorch_geometric/pull/7367. Is there a way to fix this instead of reverting? It is useful for our compile backend.

**Comment by rusty1s** [comment]
I am not sure why we need this. `torch.full` can handle both floats and tensors. I only changed the type hints because it leads to unfixable issues in TorchScript.

**Comment by rusty1s** [comment]
It is also tested here: https://github.com/pyg-team/pytorch_geometric/blob/master/test/utils/test_to_dense_batch.py#L57-L72

**Comment by piotrchmiel** [comment]
Can we stay here with fill_value as a torch.tensor? It is working correctly here and from torch. compile pov should be better as it doesn't cause torch.dynamo splitting graph in order to execute subtraction in Python. 

Let's consider following example:

```import torch

def my_custom_backend(gm, example_inputs):
    print(gm.graph)
    return gm.forward


@torch.compile(backend=my_custom_backend)
def foo(x):
    res = torch.add(x, 5)

    res = torch.max(x) - 1

    return torch.add(res, 5)

@torch.compile(backend=my_custom_backend)
def foo_item(x):
    res = torch.add(x, 5)

    res = torch.max(x).item() - 1

    return torch.add(res, 5)


print("One graph:")
foo(torch.rand(2, 3))

print("Two graphs:")
foo_item(torch.rand(2, 3)i)

```

Output:
```
One graph:
graph():
    %x : torch.Tensor [#users=2] = placeholder[target=x]
    %add : [#users=0] = call_function[target=torch.add](args = (%x, 5), kwargs = {})
    %max_1 : [#users=1] = call_function[target=torch.max](args = (%x,), kwargs = {})
    %sub : [#users=1] = call_function[target=operator.sub](args = (%max_1, 1), kwargs = {})
    %add_1 : [#users=1] = call_function[target=torch.add](args = (%sub, 5), kwargs = {})
    return (add_1,)
Two graphs:
graph():
    %x : torch.Tensor [#users=2] = placeholder[target=x]
    %add : [#users=0] = call_function[target=torch.add](args = (%x, 5), kwargs = {})
    %max_1 : [#users=1] = call_function[target=torch.max](args = (%x,), kwargs = {})
    return (max_1,)
graph():
    %add : [#users=1] = call_function[target=torch.add](args = (-0.0725749135017395, 5), kwargs = {})
    return (add,)
```

item() causes graph split, as we need to go back and execute code in Python.

**Comment by Kh4L** [comment]
I got this error:
```
  File "seal_link_pred.py", line 221, in <module>
    loss = train()
  File "seal_link_pred.py", line 196, in train
    out = model(data.x, data.edge_index, data.batch)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "seal_link_pred.py", line 173, in forward
    x = global_sort_pool(x, batch, self.k)
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/deprecation.py", line 23, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/nn/glob.py", line 25, in global_sort_pool
    return module(x, index=index)
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/nn/aggr/base.py", line 109, in __call__
    return super().__call__(x, index, ptr, dim_size, dim, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/nn/aggr/sort.py", line 34, in forward
    batch_x, _ = self.to_dense_batch(x, index, ptr, dim_size, dim,
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/nn/aggr/base.py", line 173, in to_dense_batch
    return to_dense_batch(
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/utils/to_dense_batch.py", line 121, in to_dense_batch
    out = x.new_full(size, fill_value)
```

**Comment by Kh4L** [comment]
Actually I don't get why we see this error after https://github.com/pyg-team/pytorch_geometric/pull/7392 🤔

**Comment by Kh4L** [comment]
@piotrchmiel  so seal_link_pred.py seems to be failing after  #7367 with the error pasted above

**Comment by rusty1s** [comment]
I fixed this in https://github.com/pyg-team/pytorch_geometric/pull/7412.

**Comment by Kh4L** [comment]
> I fixed this in #7412.

Thanks! Closing this PR

**Pull request closed without merging**
