### PR TITLE
Message Passing Layer of `PointGNN`

### PR DESCRIPTION
**Pull request by andreasbinder**
I closed [this](https://github.com/pyg-team/pytorch_geometric/pull/6174) pull request by mistake and solved the conflicts

### CODE REVIEW

**Review by rusty1s — COMMENTED** [review]
I think this looks great. Can we also add a simple test for this?

**Comment by andreasbinder** [comment]
Hi @rusty1s ! I am sorry to bother you but I am not sure how to write the jittable part of the test (or am I even supposed to run that part, I removed the if clause in my local test).

```
x = torch.randn(6, 3)
edge_index = torch.tensor([[0, 1, 1, 1, 2, 5], [1, 2, 3, 4, 3, 4]])
row, col = edge_index
adj = SparseTensor(row=row, col=col, sparse_sizes=(6, 6))
MLP_h = MLP([3, 64, 3])
MLP_f = MLP([6, 64, 3])
MLP_g = MLP([3, 64, 3])

conv = PointGNNConv(state_channels=3, MLP_h=MLP_h, MLP_f=MLP_f, MLP_g=MLP_g)
assert conv.__repr__() == 'PointGNNConv(3, lin_h=MLP(3, 64, 3), lin_f=MLP(6, 64, 3),lin_g=MLP(3, 64, 3))'
out = conv(x, x, edge_index)

assert out.size() == (6, 3)
assert torch.allclose(conv(x, x, adj.t()), out, atol=1e-6)

if True:
    t = '(Tensor, Tensor, Tensor) -> Tensor'
    jit = torch.jit.script(conv.jittable(t))
    assert jit(x, x, edge_index).tolist() == out.tolist()

    t = '(Tensor, Tensor, SparseTensor) -> Tensor'
    jit = torch.jit.script(conv.jittable(t))
    assert torch.allclose(jit(x, x, adj.t()), out, atol=1e-5)
```
I could not infer the error from the trace:
image
I can attach the whole trace if you think it helps. Thank you very much!

**Comment by rusty1s** [comment]
Don't worry about it, I can take care of it. Do you want to push your tests so that I can take a look?

**Comment by andreasbinder** [comment]
Amazing! I added the test file (and some annotations to the conv file) @rusty1s

**Comment by andreasbinder** [comment]
Thank you for the useful changes @rusty1s ! Just out of interest, do you know why the jittable test failed (so that I know in the future)? Thank you!

**Comment by rusty1s** [comment]
I am not so sure anymore. I think it had something do to with the missing `size=None` in `propagate` which we sadly currently need for TorchScript support :(

**Pull request merged**
