### PR TITLE
Added the `GraphMaskExplainer` algorithm

### PR DESCRIPTION
**Pull request by fork123aniket**
This PR contains implementation of how to compute `layer-wise weights` for each `edge` in order to produce `explanations` for `node-level`, `edge-level`, and `graph-level` tasks. Furthermore, this implementation is different from authors' original implementation and is fast and more memory efficient than theirs. Have added `Tests` and `Examples` of the proposed implementation in order to make the overall approach understandable.

### CODE REVIEW

**Comment by fork123aniket** [comment]
Hi @rusty1s , I am still seeking your attention on this. May I get some review comments on this PR, please??

Thank you...

**Comment by rusty1s** [comment]
Yes, we discussed how to deal with this PR and have plans to move this to `torch_geometric.contrib.explain` first in order to get this in ASAP. Would that work for you?

**Comment by fork123aniket** [comment]
Yes, it will. Please move this PR to `torch_geometric.contrib.explain` and then we'll take this PR forward from there. Thank you!!

**Comment by fork123aniket** [comment]
Hi @rusty1s, Any updates?? Can we do something to review and merge this PR ASAP??

**Review by rusty1s — APPROVED** [review]
Moved to `contrib` - feel free to extend and clean-up in a follow-up. There were some device issues I needed to fix.

**Pull request merged**
