### PR TITLE
Draft: `torch_geometric.nn.nlp.TXT2KG` and `examples/hotpot_qa.py` for recall/precision eval

### PR DESCRIPTION
**Pull request by puririshi98**
Closing/rebasing to https://github.com/pyg-team/pytorch_geometric/pull/9846

Many RAG Q+A datasets do not have existing KGs to work with. KG creation is an essential step in the real world. This is a simplistic approach, in the future hope to have more refined approaches to replace this

Deliverable: example of making a standard RAG benchmark like hotpotQA into a KG and how to measure precision/recall of retrieval

Basing on a copy of https://github.com/pyg-team/pytorch_geometric/pull/9666, will change base of PR to master once his work is merged

Now works at small scale, testing at full scale (10% of hotpot QA) soon. Goal is >=.5 precision/recall

### CODE REVIEW

**Comment by puririshi98** [comment]
> How difficult would it be to upgrade from Llama 2.0 to 3.1?

im not sure what you mean. I dont use either for this PR. if your talking about the default model for the g_retriever.py example, it should be trivial for you to swap in any LLM or GNN, thats the whole point of the framework.

**Comment by puririshi98** [comment]
@rjurney

**Comment by puririshi98** [comment]
needs rebase onto master

**Comment by rjurney** [comment]
Support for Llama 3.3 79B out today that performs as well as Llama 3.1 405B for much less money… would be awesome!

**Comment by puririshi98** [comment]
> Support for Llama 3.3 79B out today that performs as well as Llama 3.1 405B for much less money… would be awesome!

@rjurney the latest code allows a user to input any NVIDIA NIM or run any huggingface model locally. feel free to test out either model and let me know how it goes

**Pull request closed without merging**
