### PR TITLE
`GLGExplainer`

### PR DESCRIPTION
**Pull request by steveazzolin**
PR implementing  `GLGExplainer` (https://openreview.net/forum?id=OTbRTIY4YS)

### CODE REVIEW

**Comment by RBendias** [comment]
Hi @steveazzolin

thank you very much for the PR. 

After reviewing the changes in the PR, I think it would be awesome if we could break it up into smaller PRs. That would make it easier to review and provide feedback. It would also allow us to have specific discussions on different topics. The individual PRs could be based on the topics: example, visualization, metrics, and the actual method.... Wdyt?

**Comment by steveazzolin** [comment]
Thanks @RBendias for your feedback.

Yeah for me it would work.
Could you please hint me a smart way to handle the separation of this PR into smaller ones, as I'm not super familiar with contributing to open source projects?

**Comment by RBendias** [comment]
> Thanks @RBendias for your feedback.
> 
> Yeah for me it would work. Could you please hint me a smart way to handle the separation of this PR into smaller ones, as I'm not super familiar with contributing to open source projects?
> 
> I think is quite feasible to separate example and metrics from the rest, while the visualization part is embedded into the actual method as of now, following what done for `explain.Explanation`

@steveazzolin you can do this by creating new branches for each topic, copying the relevant code into these branches, and then opening new pull requests. I would aim for each pull request to have a maximum of 300-500 new lines of code.

**Comment by steveazzolin** [comment]
Sorry the PR automatically closed when I reset the repository for minimizing the changes between the current HEAD and my code.
@RBendias I split the contribution into different branches, but the main implementation is still around ~1k lines of code, because it includes all the code background code for implementing the `LogicExplainedNetwork`.
If that is ok I'll submit the new individual PRs, WDYT?

**Comment by rusty1s** [comment]
Sounds wonderful, thank you :)

**Comment by steveazzolin** [comment]
Ok great.
So I'll open a separate PR for each branch, right?
Sorry for asking, I just want to make sure to avoid clutter in the PRs :)

**Comment by RBendias** [comment]
Yes, one PR for each branch. :) I think it's enough to start with one PR, and then we move on to the next ones after we have merged the first one.

**Comment by steveazzolin** [comment]
Ok great, thanks!
Just created #7577

**Pull request closed without merging**
