### PR TITLE
Convert molecular features to floating-point values

### PR DESCRIPTION
**Pull request by aehrlich1**
Change node feature data type from long to float.

### CODE REVIEW

**Comment by rusty1s** [comment]
Thanks. This doesn't look correct to me. These are categorical features which are expected to be processed via `torch.nn.EmbeddingBag`.

**Comment by aehrlich1** [comment]
The issue arises when trying to pass the data object through a GCN that uses F.linear.

Here a small example where the problem comes up:

`import torch
import torch.nn.functional as F
from torch_geometric.utils import from_smiles
from torch_geometric.nn import GCNConv

smiles = 'COc1cccc(c2cccc(F)c2C(=O)[O-])c1'
data = from_smiles(smiles)

# data.x = data.x.float()
print(data.x.dtype, data.edge_attr.dtype, data.edge_index.dtype)
class GCN(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = GCNConv(9, 128)
        self.conv2 = GCNConv(128, 2)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index

        x = self.conv1(x, edge_index)

        return F.log_softmax(x, dim=1)

model = GCN()
model(data)
`

This will throw an error "RuntimeError: Found dtype Long but expected Float".

**Comment by rusty1s** [comment]
Yes, this is expected. The correct usage is:
```python
self.emb = torch.nn.EmbeddingBag(100, 64)

x = self.emb(data.x)
x = conv(x, edge_index)

**Comment by aehrlich1** [comment]
Ahhh I see. I must have overlooked this in the documentation. My apologies for opening the PR. It can be closed.

**Pull request closed without merging**
