### PR TITLE
Disallow `add_self_loops=True` in `GCNConv` when `normalize=False`

### PR DESCRIPTION
**Pull request by xnuohz**
Fix https://github.com/pyg-team/pytorch_geometric/issues/6251

### CODE REVIEW

**Comment by EdisonLeeeee** [comment]
Thank you for the PR, I don't think it is necessary to make these changes, as 

- `normalize` is the core operation in `GCNConv`, and in most cases, it is recommended to set it to `True` when using `GCNConv` as the convolution layer.
- While there are situations where using `GCNConv` without normalization but with self-loops might be desired, it is possible to manually add self-loops during the forward pass or data preprocessing. In such cases, it might be more appropriate to consider using `SAGEConv`.
- To support such cases, adding the functionality of self-loops without normalization to `GCNConv` would require introducing additional code, which could potentially make the implementation more complex and harder to read.

Perhaps we can simply add a warning when `normalize=False` but `add_self_loops=True`, WDYT?

**Comment by xnuohz** [comment]
> Thank you for the PR, I don't think it is necessary to make these changes, as
> 
> * `normalize` is the core operation in `GCNConv`, and in most cases, it is recommended to set it to `True` when using `GCNConv` as the convolution layer.
> * While there are situations where using `GCNConv` without normalization but with self-loops might be desired, it is possible to manually add self-loops during the forward pass or data preprocessing. In such cases, it might be more appropriate to consider using `SAGEConv`.
> * To support such cases, adding the functionality of self-loops without normalization to `GCNConv` would require introducing additional code, which could potentially make the implementation more complex and harder to read.
> 
> Perhaps we can simply add a warning when `normalize=False` but `add_self_loops=True`, WDYT?

Generally agree. There are two solutions I've considered

- Directly forbid `normalize=False`, indeed in most cases we will not set it like this
- Support `normalize=False` to make sure the return is correct, since currently the results are incorrect when `add_self_loops=True`.

And I chose the 2nd one, haha.

**Review by rusty1s — COMMENTED** [review]
Thank you. This is actually a breaking change which we would need to avoid. As such, can we make `add_self_loops` be of type `Optional[bool] = None`, and set it based on `normalize=False/True` whenever it is not explicitly passed?

**Comment by xnuohz** [comment]
> Thank you. This is actually a breaking change which we would need to avoid. As such, can we make `add_self_loops` be of type `Optional[bool] = None`, and set it based on `normalize=False/True` whenever it is not explicitly passed?

How about `add_self_loops=False` for `normalize=False` and `add_self_loops=True` for `normalize=True` ? If so, then a warning is needed when we explicitly pass `normalize=False` and `add_self_loops=True`.

**Comment by rusty1s** [comment]
I just read @EdisonLeeeee's post, and need to agree with this. Normalization in `GCNConv` code is quite complex and we shouldn't move away from the original implementation too much.

**Review by rusty1s — APPROVED** [review]

**Pull request merged**
