### PR TITLE
Updated docstring for shape info

### PR DESCRIPTION
**Pull request by saiden89**
As proposed in #3573, here is my take on the first chunk of convolutional layers in PyG. More will follow soon.

### CODE REVIEW

**Comment by saiden89** [comment]
Thanks for the corrections. Indeed, I was also wondering how to solve some inconsistencies in notation. So I guess now all features are F instead of H. How about the attention heads? Some papers refer to them as K (like GAT) some others to H. Do you think it would be better to follow the original article of to use a universal notation in PyG?

**Review by rusty1s — APPROVED** [review]
This is great, thank you :)
I further changed the CSS layout and made some style changes.

**Comment by rusty1s** [comment]
I think it's better to have a universal notation, and I like the following:
* `|V|`: number of nodes
* `|E|`: number of edges
* `F`: node feature size
* `D`: edge feature size
* `H`: number of heads
* `L`: number of layers

**Comment by saiden89** [comment]
I have another batch of the updated docstring. Is it possible to reopen this pull request or do I make a new one?

**Pull request merged**
