### PR TITLE
Adapt cuGraph examples to new API

### PR DESCRIPTION
**Pull request by alexbarghi-nv**
Updates the cuGraph examples to use the new non-dask API.  Adds a new multinode cuGraph example.

### CODE REVIEW

**Comment by alexbarghi-nv** [comment]
@puririshi98

**Comment by puririshi98** [comment]
LGTM, @rusty1s @akihironitta anything else needed to merge?

**Comment by rusty1s** [comment]
@alexbarghi-nv Can you give me write access to your fork?

**Comment by alexbarghi-nv** [comment]
@rusty1s I just gave you access

**Review by rusty1s — APPROVED** [review]
Super :)

**Pull request merged**
