### PR TITLE
Multi-GPU Taobao example

### PR DESCRIPTION
**Pull request by puririshi98**
on Luna (8xA100):
	1 gpu: ~22 it/s
        8 gpu: ~15 it/s

### CODE REVIEW

**Review by akihironitta — COMMENTED** [review]
(Pls ignore my comment here if still wip!)

I think the example is still incomplete because the model is not synced across multiple processes (as `DistributedDataParallel` isn't used). Also, I'm still trying to catch up on distributed training on a large graph, but if I understand correctly, this example has all processes looking at the same duplicate graph.

**Comment by puririshi98** [comment]
oh haha good catch i was copying code together from two examples and missed copying that part

**Review by akihironitta — COMMENTED** [review]
I might be missing something, but I'm still not sure if this is complete because each process looks at all of the links. Instead, we should split a set of target links into subsets of target links so that each process will only look at a subset, no?

**Comment by puririshi98** [comment]
with latest changes it is now failing (need to debug when i have bandwidth):
```
Let's use 8 GPUs!
Traceback (most recent call last):
  File "/opt/pyg/pytorch_geometric/examples/multi_gpu/taobao_multigpu_large.py", line 266, in <module>
    mp.spawn(run_train,
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 6 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/opt/pyg/pytorch_geometric/examples/multi_gpu/taobao_multigpu_large.py", line 196, in run_train
    for batch in train_loader:
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 441, in __iter__
    return self._get_iterator()
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/loader/link_loader.py", line 297, in _get_iterator
    return super()._get_iterator()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1042, in __init__
    w.start()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 58, in _launch
    self.pid = util.spawnv_passfds(spawn.get_executable(),
  File "/usr/lib/python3.10/multiprocessing/util.py", line 452, in spawnv_passfds
    return _posixsubprocess.fork_exec(
ValueError: bad value(s) in fds_to_keep
```

**Comment by puririshi98** [comment]
@akihironitta its working now
Epoch: 01, Loss: 0.000099, Val: 0.9370, Test: 0.9370

**Review by akihironitta — APPROVED** [review]
LGTM!

**Pull request merged**
