### PR TITLE
[Code Coverage] `data/view.py`

### PR DESCRIPTION
**Pull request by EulerPascal404**
Created code coverage for `data/view.py`.

### CODE REVIEW

**Comment by EulerPascal404** [comment]
@rusty1s It seems that the `Testing PyTorch nightly / latest_pytest (pull_request)` is failing on some other file - not related to the files I committed - which is causing an unsuccessful check. Do I need to worry about this specific check? If not, can you please review this PR.

**Comment by rusty1s** [comment]
This seems to be just a flake, should be fixed now.

**Comment by EulerPascal404** [comment]
@rusty1s I think this is ready for merging.

**Comment by EulerPascal404** [comment]
@rusty1s Can you please review this PR?

**Comment by rusty1s** [comment]
Sorry for the delay, I am on vacation this week. Will merge early next week.

**Comment by EulerPascal404** [comment]
> Sorry for the delay, I am on vacation this week. Will merge early next week.

Of course, no problem!

**Review by rusty1s — APPROVED** [review]

**Pull request merged**
