### PR TITLE
Fix CUDA error in `GATConv` on empty edges

### PR DESCRIPTION
**Pull request by puririshi98**
```
E         File "/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/nn/conv/gat_conv.py", line 247, in forward
E           alpha = self.edge_updater(edge_index, alpha=alpha, edge_attr=edge_attr)
E         File "/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/nn/conv/message_passing.py", line 508, in edge_updater
E           out = self.edge_update(**edge_kwargs)
E         File "/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/nn/conv/gat_conv.py", line 289, in edge_update
E           alpha = softmax(alpha, index, ptr, size_i)
E         File "/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/utils/softmax.py", line 78, in softmax
E           out_sum = scatter(out, index, dim, dim_size=N, reduce='sum') + 1e-16
E         File "/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/utils/scatter.py", line 74, in scatter
E           return src.new_zeros(size).scatter_add_(dim, index, src)
E       RuntimeError: CUDA error: invalid configuration argument
E       Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

my minor change fixes it and training proceeds as expected after

### CODE REVIEW

**Comment by rusty1s** [comment]
Hi @puririshi98, I added a test for this, but cannot really reproduce this on my end. Does the test crash without your fix? Ideally, can we fix this in `utils.scatter` in a general way rather than solely fixing this for `GATConv`?

**Comment by puririshi98** [comment]
> Hi @puririshi98, I added a test for this, but cannot really reproduce this on my end. Does the test crash without your fix?

yeah the test does crash without the fix, but i do agree that perhaps this can be done more generally

**Comment by puririshi98** [comment]
@rusty1s spent some time trying to get it working by applying a similar fix to scatter instead of gat_conv, however after many attempts i still get super ugly/hard to understand cuda errors. will continue investigated, just a headsup on progress, (or lack thereof😭). so far the only thing that works for me is returning early in the edge_update function. when i try to return early in scatter or softmax, i end up with hard to understand cuda runtime errors

**Comment by puririshi98** [comment]
so far the only other way i can avoid super ugly cuda runtime errors by adding:
```
        if edge_index.is_cuda and torch.numel(edge_index)==0:
            return kwargs["alpha"][0] # return empty source
```
to the top of MessagePassing edge updater: https://github.com/pyg-team/pytorch_geometric/blob/ccaf40b361635121e00324df022a8235f08893b9/torch_geometric/nn/conv/message_passing.py#L484

after this change:
this gives:
```
E         File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
E           fn(i, *args)
E         File "/opt/pyg/gnn-platform/gp/workflow/trainers/utils.py", line 65, in run_fit
E           spawnable_trainer.fit_process()
E         File "/opt/pyg/gnn-platform/gp/workflow/trainers/spawned_worker.py", line 152, in fit_process
E           self.do_train_epoch()
E         File "/opt/pyg/gnn-platform/gp/workflow/trainers/spawned_worker.py", line 195, in do_train_epoch
E           metrics = self.step(batch, mode="train")
E         File "/opt/pyg/gnn-platform/gp/workflow/trainers/spawned_worker.py", line 283, in step
E           output, target, loss = self.forward_pass(batch, mode)
E         File "/opt/pyg/gnn-platform/gp/workflow/trainers/spawned_worker.py", line 267, in forward_pass
E           output = self.model(batch)
E         File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
E           return forward_call(*args, **kwargs)
E         File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 1162, in forward
E           output = self._run_ddp_forward(*inputs, **kwargs)
E         File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 1112, in _run_ddp_forward
E           return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
E         File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
E           return forward_call(*args, **kwargs)
E         File "/opt/pyg/gnn-platform/gp/models/pyg/hetero_module.py", line 138, in forward
E           return self.model(batch)
E         File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
E           return forward_call(*args, **kwargs)
E         File "/opt/pyg/gnn-platform/gp/models/pyg/hetero_module.py", line 33, in forward
E           h = layer(batch, h)
E         File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
E           return forward_call(*args, **kwargs)
E         File "/opt/pyg/gnn-platform/gp/models/pyg/hetero_conv_layer.py", line 154, in forward
E           h = self.conv(x, edge_index_dict)
E         File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
E           return forward_call(*args, **kwargs)
E         File "/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/nn/conv/hetero_conv.py", line 138, in forward
E           out = conv((x_dict[src], x_dict[dst]), edge_index, *args,
E         File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
E           return forward_call(*args, **kwargs)
E         File "/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/nn/conv/gat_conv.py", line 252, in forward
E           out = self.propagate(edge_index, x=x, alpha=alpha, size=size)
E         File "/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/nn/conv/message_passing.py", line 444, in propagate
E           out = self.message(**msg_kwargs)
E         File "/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/nn/conv/gat_conv.py", line 291, in message
E           return alpha.unsqueeze(-1) * x_j
E       RuntimeError: The size of tensor a (45185) must match the size of tensor b (0) at non-singleton dimension 0
```

this would still result in me needing to make changes to gat_conv, but i think that would be fine since afaik edge_updater is only used in gat_conv.
Screen Shot 2023-03-16 at 3 28 43 PM
@rusty1s lmk if u think this is a sufficient fix, and i can implement it

**Comment by rusty1s** [comment]
I personally would like to avoid having this fix purely for `GATConv`, on the other hand it is hard for me to help here without being able to reproduce this issue.

> `E       RuntimeError: The size of tensor a (45185) must match the size of tensor b (0) at non-singleton dimension 0`

This is a bit confusing to me. Why would `alpha` be able to contain elements if there exists no edges/nodes?

**Comment by puririshi98** [comment]
thanks for your comment @rusty1s, i figured out how to solve the bug generally by only making changes to message passing

**Review by rusty1s — APPROVED** [review]

**Pull request merged**
