### PR TITLE
Spectral Modularity Pool layer

### PR DESCRIPTION
**Pull request by fork123aniket**
Implementation of spectral modularity pooling that not only coarsen the graphs but can also be used to cluster the nodes of any graph.

### CODE REVIEW

**Comment by fork123aniket** [comment]
All the issues listed in PR#4114 have been addressed. Have added **_MLP_**, which can be seen in lines 69, 71, and 73 of **_dense_dmon_pool.py_**. Moreover, have also added hints to the function definition on line 61.

**Comment by rusty1s** [comment]
Any idea why the tests are failing?

**Comment by fork123aniket** [comment]
Yes. `torch_geometric.nn.MLP` is the cause of why the tests have failed. To mitigate this, I just superseded the MLPs with `Linear` layers as what I did in the last commit. Moreover, why `torch_geometric.nn.MLP` not the right choice over `Linear` is because it doesn't allow me to set `act` variable to `torch.nn.SELU` which is what the original solution uses. When I tried to access this `act` variable of `torch_geometric.nn.MLP`, it threw `ArgumentError`.

**Comment by rusty1s** [comment]
Mh weird. You should be able to set the act of `MLP` to SELU, e.g., via `MLP(…, act=SELU())`.

**Comment by fork123aniket** [comment]
image

**Comment by fork123aniket** [comment]
Yes, I did. However, I got the error (shown in the screenshot attached below). Moreover, even if we get it somehow to work, 11 of 18 total tests will again get failed. Please let me know if we can still put `Linear` to some use instead of `torch_geometric.nn.MLP`.

image

**Comment by rusty1s** [comment]
@fork123aniket I modified the code to make use of `MLP`. For this, we need to delay the import to avoid circular import. I think this makes the code more clear. Note that the `act` argument of `MLP` can only be modfied in case you have PyG master installed. This feature just got recently added.

**Comment by fork123aniket** [comment]
Hmm.... Yes, you're right!! The code seems more evident now. So, what are we doing next with this PR? Are all the files ready to get merged or do we still need any further modifications somewhere in the given four committed files?? Please let me know your thoughts.......

**Comment by rusty1s** [comment]
It looks good from my side. I will make another pass tomorrow. Thank you! Feel free to send your other PR in a separate branch.

**Comment by fork123aniket** [comment]
@rusty1s Could you please help closing this PR just by merging the committed files??

**Review by rusty1s — APPROVED** [review]
Indeed. Thanks for your contribution!

**Pull request merged**
