### PR TITLE
Update cugraph conv layers for `pylibcugraphops=23.04`

### PR DESCRIPTION
**Pull request by tingyu66**
This PR updates cugraph models to reflect breaking changes in `pylibcugraphops=23.04`. 
~~Right now, it is **blocked** by RAPIDS 23.04 release.~~

CC: @matthiaskohl @stadlmax

### CODE REVIEW

**Review by rusty1s — APPROVED** [review]
LGTM. Feel free to merge once you released the new version.

**Review by MatthiasKohl — APPROVED** [review]
Looks good from my side, too, if all the tests are passing. 23.04 RAPIDS release should be on April 12th, so this will stay blocked for at least another 2 weeks.

**Comment by tingyu66** [comment]
Hi @rusty1s, we have a bit of a compatibility issue here among RAPIDS packages, due to the the different release cadence of Rapids and PyG. The upcoming cugraph 23.04 release is pinned to PyG 2.3.0, however, PyG 2.3.0 was release with cugraph-ops 23.02 (since we did not want to break users at the time).

Is there a chance that we can have a minor release that incorporates this PR? Apologies for the late communication, we will plan this in future releases.

CC: @MatthiasKohl @alexbarghi-nv

**Comment by rusty1s** [comment]
I think this is possible. Let's discuss in person today.

**Comment by tingyu66** [comment]
@rusty1s I repurpose this PR to support both 23.02 and 23.04 APIs, feel free to check again. Thanks!

**Review by rusty1s — APPROVED** [review]

**Comment by tingyu66** [comment]
> I think this is possible. Let's discuss in person today.

Hey @rusty1s , just want to follow up with the minor release request. Do we have any blockers? Thanks!

**Comment by rusty1s** [comment]
No blockers, let me create `2.3.1` tomorrow :)

**Pull request merged**
