### PR TITLE
Ensure data is on the same device in `knn_graph`

### PR DESCRIPTION
**Pull request by mzamini92**
we can directly move the tensors to the desired device using the `to()` method provided by PyTorch. This ensures that all tensors within the data object are on the same device before calling `knn_graph`.
This seems to be a solution for #7475 issue.

### CODE REVIEW

**Comment by rusty1s** [comment]
Thanks for the PR. I am not totally sure though why we need it. I don't think we should do any implicit device transfers, and `knn_graph` should already fail on tensors on different devices. Can you clarify?

**Comment by mzamini92** [comment]
> Thanks for the PR. I am not totally sure though why we need it. I don't think we should do any implicit device transfers, and `knn_graph` should already fail on tensors on different devices. Can you clarify?

Thanks for going through my solution. The reason for this is that `knn_graph` might not raise an error when the input tensors are on different devices. Instead, it may silently produce incorrect results or unexpected behavior. By explicitly transferring the input tensor to the correct device before calling knn_graph, we ensure that the function operates correctly and returns valid edge indices.
While it's possible that `knn_graph` should raise an error when the input tensors are on different devices, the proposed fix provides a more robust solution by handling the device transfer explicitly. This ensures that the function works as intended and avoids potential issues with mixed-device tensors.

**Comment by rusty1s** [comment]
I cannot really reproduce this via
```python
import torch

from torch_geometric.nn import knn_graph

x = torch.rand((10, 2))
batch = torch.tensor([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

edge_index_cpu = knn_graph(x, k=2, batch=batch.cuda())
print(edge_index_cpu)
edge_index_cuda = knn_graph(x.cuda(), k=2, batch=batch)
print(edge_index_cuda)
```
Both calls fail as expected. I am a bit hesitant with automatic device transfers in this function, as it will slow down your program if the inputs are not on the correct device. This is a user error, and I think failing out here is the correct approach.

**Comment by mzamini92** [comment]
> I cannot really reproduce this via
> 
> ```python
> import torch
> 
> from torch_geometric.nn import knn_graph
> 
> x = torch.rand((10, 2))
> batch = torch.tensor([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])
> 
> edge_index_cpu = knn_graph(x, k=2, batch=batch.cuda())
> print(edge_index_cpu)
> edge_index_cuda = knn_graph(x.cuda(), k=2, batch=batch)
> print(edge_index_cuda)
> ```
> 
> Both calls fail as expected. I am a bit hesitant with automatic device transfers in this function, as it will slow down your program if the inputs are not on the correct device. This is a user error, and I think failing out here is the correct approach.

yes this error makes sense to show up. since this was mentioned as bug I thought maybe it would be a good idea that we explicitly transferring the data. but I agree with you. The code would be more robust but a little bit might be slower. it is not considerable though.

**Comment by rusty1s** [comment]
Thanks for your response. In that case, shall we close this PR? Alternatively, we can add a warning whenever we perform memory transfers in this function. This would work for me as well.

**Comment by mzamini92** [comment]
> Thanks for your response. In that case, shall we close this PR? Alternatively, we can add a warning whenever we perform memory transfers in this function. This would work for me as well.

The Alternative sounds like a good option too. I modified the code accordingly to show the Warning. In this modified version, a warning message is printed when the input data `(data.pos)` is on CUDA. The data is then transferred to the CPU `(data.pos.cpu())` before calling the knn_graph function. This ensures that the knn_graph function is always called with CPU data. if that's not what you meant then you can go ahead and close the PR. Thank you for your time.

**Pull request merged**
