### PR TITLE
Replace `Union` type hints

### PR DESCRIPTION
**Pull request by rusty1s**

### CODE REVIEW

**Comment by EdisonLeeeee** [comment]
@rusty1s Should we also replace something like `Optional[int]` with `int | None`?

**Comment by rusty1s** [comment]
> Should we also replace something like Optional[int] with int | None?

What do you prefer? I actually like `Optional` syntax more (but no strong opinion).

**Comment by EdisonLeeeee** [comment]
> > Should we also replace something like Optional[int] with int | None?
> 
> What do you prefer? I actually like `Optional` syntax more (but no strong opinion).

I prefer using `| None` as it explicitly indicates the optional `None` choices, especially in cases where `None` is not the default value. I don't have a strong opinion either - just a proposal :)

**Comment by rusty1s** [comment]
Looks like we cannot merge this PR here yet anyway due to broken JIT tests.

**Pull request closed without merging**
