### PR TITLE
Addition of temporal layers

### LINKED ISSUE #3230: [Roadmap] Temporal Graph Support

### PR DESCRIPTION
**Pull request by rajveer43**
close #3230

### CODE REVIEW

**Review by akihironitta — COMMENTED** [review]
Hi @rajveer43, thanks for working on this! I'm trying to understand the context to review this change.

Were there any discussions on how we want to add temporal layers and models somewhere (on GitHub issues/discussions, PyG Slack, etc.)? Do you know if this PR is related to #8063?

**Comment by rajveer43** [comment]
> Hi @rajveer43, thanks for working on this! I'm trying to understand the context to review this change.
> 
> Were there any discussions on how we want to add temporal layers and models somewhere (on GitHub issues/discussions, PyG Slack, etc.)? Do you know if this PR is related to #8063?

this PR is related to #3230

**Comment by flandolfi** [comment]
Be aware that this is just a cut and paste of the contents of the `nn` folder of PyTorch-Geometric-Temporal: https://github.com/benedekrozemberczki/pytorch_geometric_temporal/tree/master/torch_geometric_temporal/nn

**Comment by rajveer43** [comment]
> Be aware that this is just a cut and paste of the contents of the `nn` folder of PyTorch-Geometric-Temporal: https://github.com/benedekrozemberczki/pytorch_geometric_temporal/tree/master/torch_geometric_temporal/nn


can we have a discussion how we are going to approach the development of temporal layers?

**Pull request closed without merging**
