### PR TITLE
feat: add `CornellTemporalHyperGraphDatasets`

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
Reference: #8501 #7312 

Request for Review: @rusty1s @wsad1

This PR aims to add HyperGraph datasets consisting of timestamped simplices where each simplex is a set of nodes. Released with the paper [Simplicial Closure and higher-order link prediction](https://huggingface.co/papers/1802.06916).

Notes:
> "[In compliance with PEP 8 and PEP 257, Ruff prefers double quotes for triple quoted strings and docstrings even when using quote-style = "single".](https://docs.astral.sh/ruff/settings/#format_quote-style)". 

Thus even with pre-commit passing there are changes which convert `'` to `"`. Should probably look into setting the `quote-style` property to `"single"`, if single quotes are desired. That way it can be enforced via pre-commit as well.

---
_**Update 26th March 2024**: There are multiple datasets which follow a similar processing and loading workflow. Therefore, I have refactored to make a single `CornellTemporalHyperGraphDataset` class. I'm still encountering errors with the test on windows, would appreciate some help on this_

### CODE REVIEW

**Comment by SauravMaheshkar** [comment]
I can't figure out this path error on windows, would appreciate some help on this.

**Comment by SauravMaheshkar** [comment]
@rusty1s I ended up refactoring to allow for all datasets to use the same class

**Comment by SauravMaheshkar** [comment]
Gentle ping: @rusty1s

**Review by rusty1s — APPROVED** [review]
Cool :)

**Pull request merged**
