### PR TITLE
Add `AddRemainingSelfLoops` transform

### PR DESCRIPTION
**Pull request by bwroblew**
This PR adds the `AddRemainingSelfLoops` transform to generate only remaining self-loops instead of generating them on all the vertices like in the `AddSelfLoops` transform.

### CODE REVIEW

**Review by wsad1 — COMMENTED** [review]
@bwroblew , good work!
Lets add another transform as you suggested, thats more cleaner. 
Other than that the code and tests look good.

**Review by wsad1 — APPROVED** [review]

**Comment by wsad1** [comment]
@bwroblew if its ok, could you please give edit access to `maintainers`, for this and future PRs.

**Comment by bwroblew** [comment]
> @bwroblew if its ok, could you please give edit access to `maintainers`, for this and future PRs.

I'm afraid it's not possible since our fork lives under the `graphcore` organization... I didn't know that limitation but don't see an option here in the PR and just discovered there is an issue for that - https://github.com/orgs/community/discussions/5634. It has not been resolved yet.

I believe @rusty1s have access since was added as an outside collaborator with write access to our fork. Unfortunately, I don't have access to add outside collaborators to the fork, please let me discuss that inside Graphcore and see what we can do about that.

**Comment by wsad1** [comment]
@bwroblew ah I see. 
In that case can you resolve conflicts and merge this PR.

**Comment by rusty1s** [comment]
Thanks all. Let me take care of merging :)

**Comment by bwroblew** [comment]
Thanks @rusty1s! I've started an internal discussion and will try to make it easier for future PRs somehow :)

**Pull request merged**
