### PR TITLE
Add PyTorch SparseTensor support for `GCNConv` and `gcn_norm`

### PR DESCRIPTION
**Pull request by EdisonLeeeee**
For `gcn_norm`, a PyTorch SparseTensor is converted to `torch_sparse.SparseTensor` and then converted back. Not really like this but have no better solution.

### CODE REVIEW

**Review by rusty1s — COMMENTED** [review]
Thanks for this PR. I think this gets really tricky to implement with TorchScript support. Sadly, they do not pass in this PR but I also failed to make them work :(

**Comment by EdisonLeeeee** [comment]
Yeah, I have been blocked by this problem and also failed to find a solution these days. It seems we should drop the TorchScript support for PyTorch SparseTensor for now.

**Comment by rusty1s** [comment]
Yeah, we don't have support for this anyway yet. The challenge is to ensure that original TorchScript support is maintained :(

**Comment by EdisonLeeeee** [comment]
Noticed now. The problem seems related to `is_torch_sparse_tensor` - unable to distinguish between the `Tensor`(dense) and `torch.sparse.Tensor` when converting to torchscript :(

**Comment by EdisonLeeeee** [comment]
@rusty1s I've made the tests passed with some changes on `gcn_norm` when dealing with `torch.sparse.Tensor`, it is somehow tricky though.

**Review by rusty1s — APPROVED** [review]
This is quite clever. Thank you!

**Pull request merged**
