### PR TITLE
Respect tuple of `data` objects in `Dataset.num_classes`

### PR DESCRIPTION
**Pull request by puririshi98**
https://github.com/pyg-team/pytorch_geometric/issues/6782#issuecomment-1460485546

> Traceback (most recent call last):
>   File "argva_node_clustering.py", line 130, in <module>
>     plot_points(test_data, colors)
>   File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "argva_node_clustering.py", line 121, in plot_points
>     for i in range(dataset.num_classes):
>   File "/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/data/in_memory_dataset.py", line 175, in __getattr__
>     raise AttributeError(f"'{self.__class__.__name__}' object has no "
> AttributeError: 'Planetoid' object has no attribute 'num_classes'

### CODE REVIEW

**Comment by rusty1s** [comment]
Mh, `num_classes` is a property of `InMemoryDataset`, so I think the issue lies somewhere else. I cannot reproduce this :(

**Comment by puririshi98** [comment]
> I cannot reproduce this :(

yeah me neither after updating everything to latest, i think our CI was just run at the worst possible time lolz

**Comment by puririshi98** [comment]
```
root@c8911ae473ab:/workspace/examples# python3 argva_node_clustering.py
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.x
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.tx
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.allx
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.y
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.ty
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.ally
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.graph
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.test.index
Processing...
Done!
Epoch: 001, Loss: 5.326, AUC: 0.659, AP: 0.680, Completeness: 0.092, Homogeneity: 0.089, NMI: 0.090
Epoch: 002, Loss: 5.231, AUC: 0.646, AP: 0.679, Completeness: 0.083, Homogeneity: 0.084, NMI: 0.084
Epoch: 003, Loss: 4.965, AUC: 0.643, AP: 0.680, Completeness: 0.080, Homogeneity: 0.077, NMI: 0.078
Epoch: 004, Loss: 4.853, AUC: 0.642, AP: 0.681, Completeness: 0.075, Homogeneity: 0.072, NMI: 0.074
Epoch: 005, Loss: 4.662, AUC: 0.643, AP: 0.683, Completeness: 0.072, Homogeneity: 0.068, NMI: 0.070
Epoch: 006, Loss: 4.415, AUC: 0.646, AP: 0.686, Completeness: 0.061, Homogeneity: 0.055, NMI: 0.058
Epoch: 007, Loss: 4.423, AUC: 0.650, AP: 0.690, Completeness: 0.073, Homogeneity: 0.070, NMI: 0.072
Epoch: 008, Loss: 4.218, AUC: 0.656, AP: 0.694, Completeness: 0.079, Homogeneity: 0.075, NMI: 0.077
Epoch: 009, Loss: 4.022, AUC: 0.662, AP: 0.698, Completeness: 0.082, Homogeneity: 0.077, NMI: 0.080
Epoch: 010, Loss: 3.863, AUC: 0.667, AP: 0.701, Completeness: 0.086, Homogeneity: 0.080, NMI: 0.083
Epoch: 011, Loss: 3.709, AUC: 0.670, AP: 0.702, Completeness: 0.089, Homogeneity: 0.084, NMI: 0.086
Epoch: 012, Loss: 3.560, AUC: 0.674, AP: 0.705, Completeness: 0.092, Homogeneity: 0.087, NMI: 0.089
Epoch: 013, Loss: 3.488, AUC: 0.683, AP: 0.711, Completeness: 0.138, Homogeneity: 0.134, NMI: 0.136
Epoch: 014, Loss: 3.201, AUC: 0.698, AP: 0.723, Completeness: 0.161, Homogeneity: 0.158, NMI: 0.159
Epoch: 015, Loss: 3.118, AUC: 0.721, AP: 0.743, Completeness: 0.169, Homogeneity: 0.167, NMI: 0.168
Epoch: 016, Loss: 2.924, AUC: 0.725, AP: 0.752, Completeness: 0.197, Homogeneity: 0.194, NMI: 0.196
Epoch: 017, Loss: 2.820, AUC: 0.704, AP: 0.731, Completeness: 0.177, Homogeneity: 0.174, NMI: 0.176
Epoch: 018, Loss: 2.718, AUC: 0.686, AP: 0.713, Completeness: 0.180, Homogeneity: 0.176, NMI: 0.178
Epoch: 019, Loss: 2.812, AUC: 0.682, AP: 0.708, Completeness: 0.183, Homogeneity: 0.179, NMI: 0.181
Epoch: 020, Loss: 2.838, AUC: 0.690, AP: 0.714, Completeness: 0.192, Homogeneity: 0.191, NMI: 0.191
Epoch: 021, Loss: 2.871, AUC: 0.714, AP: 0.732, Completeness: 0.250, Homogeneity: 0.254, NMI: 0.252
Epoch: 022, Loss: 2.861, AUC: 0.752, AP: 0.766, Completeness: 0.263, Homogeneity: 0.267, NMI: 0.265
Epoch: 023, Loss: 2.840, AUC: 0.781, AP: 0.791, Completeness: 0.286, Homogeneity: 0.287, NMI: 0.287
Epoch: 024, Loss: 2.823, AUC: 0.771, AP: 0.772, Completeness: 0.277, Homogeneity: 0.278, NMI: 0.277
Epoch: 025, Loss: 2.939, AUC: 0.742, AP: 0.745, Completeness: 0.238, Homogeneity: 0.237, NMI: 0.238
Epoch: 026, Loss: 3.130, AUC: 0.725, AP: 0.733, Completeness: 0.242, Homogeneity: 0.243, NMI: 0.242
Epoch: 027, Loss: 3.450, AUC: 0.727, AP: 0.739, Completeness: 0.238, Homogeneity: 0.240, NMI: 0.239
Epoch: 028, Loss: 3.728, AUC: 0.742, AP: 0.754, Completeness: 0.227, Homogeneity: 0.227, NMI: 0.227
Epoch: 029, Loss: 3.938, AUC: 0.765, AP: 0.775, Completeness: 0.232, Homogeneity: 0.230, NMI: 0.231
Epoch: 030, Loss: 4.025, AUC: 0.784, AP: 0.790, Completeness: 0.294, Homogeneity: 0.297, NMI: 0.296
Epoch: 031, Loss: 4.216, AUC: 0.788, AP: 0.790, Completeness: 0.332, Homogeneity: 0.340, NMI: 0.336
Epoch: 032, Loss: 4.307, AUC: 0.780, AP: 0.781, Completeness: 0.315, Homogeneity: 0.316, NMI: 0.316
Epoch: 033, Loss: 4.348, AUC: 0.772, AP: 0.774, Completeness: 0.314, Homogeneity: 0.314, NMI: 0.314
Epoch: 034, Loss: 4.432, AUC: 0.768, AP: 0.773, Completeness: 0.323, Homogeneity: 0.324, NMI: 0.323
Epoch: 035, Loss: 4.459, AUC: 0.770, AP: 0.777, Completeness: 0.321, Homogeneity: 0.324, NMI: 0.323
Epoch: 036, Loss: 4.538, AUC: 0.776, AP: 0.782, Completeness: 0.322, Homogeneity: 0.328, NMI: 0.325
Epoch: 037, Loss: 4.627, AUC: 0.783, AP: 0.788, Completeness: 0.325, Homogeneity: 0.330, NMI: 0.328
Epoch: 038, Loss: 4.494, AUC: 0.787, AP: 0.789, Completeness: 0.324, Homogeneity: 0.325, NMI: 0.324
Epoch: 039, Loss: 4.493, AUC: 0.788, AP: 0.785, Completeness: 0.324, Homogeneity: 0.323, NMI: 0.324
Epoch: 040, Loss: 4.510, AUC: 0.787, AP: 0.780, Completeness: 0.324, Homogeneity: 0.320, NMI: 0.322
Epoch: 041, Loss: 4.530, AUC: 0.782, AP: 0.774, Completeness: 0.328, Homogeneity: 0.316, NMI: 0.322
Epoch: 042, Loss: 4.583, AUC: 0.772, AP: 0.766, Completeness: 0.327, Homogeneity: 0.308, NMI: 0.317
Epoch: 043, Loss: 4.660, AUC: 0.763, AP: 0.757, Completeness: 0.323, Homogeneity: 0.298, NMI: 0.310
Epoch: 044, Loss: 4.778, AUC: 0.755, AP: 0.751, Completeness: 0.309, Homogeneity: 0.287, NMI: 0.297
Epoch: 045, Loss: 4.727, AUC: 0.750, AP: 0.747, Completeness: 0.308, Homogeneity: 0.285, NMI: 0.296
Epoch: 046, Loss: 4.666, AUC: 0.748, AP: 0.745, Completeness: 0.306, Homogeneity: 0.282, NMI: 0.294
Epoch: 047, Loss: 4.808, AUC: 0.749, AP: 0.745, Completeness: 0.300, Homogeneity: 0.275, NMI: 0.287
Epoch: 048, Loss: 4.809, AUC: 0.754, AP: 0.748, Completeness: 0.298, Homogeneity: 0.271, NMI: 0.284
Epoch: 049, Loss: 4.781, AUC: 0.761, AP: 0.752, Completeness: 0.300, Homogeneity: 0.272, NMI: 0.285
Epoch: 050, Loss: 4.836, AUC: 0.769, AP: 0.756, Completeness: 0.298, Homogeneity: 0.270, NMI: 0.283
Epoch: 051, Loss: 4.705, AUC: 0.777, AP: 0.761, Completeness: 0.301, Homogeneity: 0.271, NMI: 0.285
Epoch: 052, Loss: 4.644, AUC: 0.784, AP: 0.766, Completeness: 0.307, Homogeneity: 0.274, NMI: 0.290
Epoch: 053, Loss: 4.549, AUC: 0.791, AP: 0.770, Completeness: 0.304, Homogeneity: 0.267, NMI: 0.284
Epoch: 054, Loss: 4.667, AUC: 0.796, AP: 0.773, Completeness: 0.307, Homogeneity: 0.270, NMI: 0.287
Epoch: 055, Loss: 4.532, AUC: 0.800, AP: 0.775, Completeness: 0.323, Homogeneity: 0.289, NMI: 0.305
Epoch: 056, Loss: 4.428, AUC: 0.803, AP: 0.776, Completeness: 0.331, Homogeneity: 0.299, NMI: 0.314
Epoch: 057, Loss: 4.475, AUC: 0.804, AP: 0.777, Completeness: 0.300, Homogeneity: 0.281, NMI: 0.290
Epoch: 058, Loss: 4.357, AUC: 0.806, AP: 0.776, Completeness: 0.303, Homogeneity: 0.285, NMI: 0.294
Epoch: 059, Loss: 4.321, AUC: 0.807, AP: 0.775, Completeness: 0.307, Homogeneity: 0.289, NMI: 0.298
Epoch: 060, Loss: 4.305, AUC: 0.807, AP: 0.775, Completeness: 0.313, Homogeneity: 0.304, NMI: 0.309
Epoch: 061, Loss: 4.257, AUC: 0.809, AP: 0.776, Completeness: 0.317, Homogeneity: 0.308, NMI: 0.312
Epoch: 062, Loss: 4.261, AUC: 0.812, AP: 0.778, Completeness: 0.326, Homogeneity: 0.318, NMI: 0.322
Epoch: 063, Loss: 4.229, AUC: 0.815, AP: 0.781, Completeness: 0.324, Homogeneity: 0.316, NMI: 0.320
Epoch: 064, Loss: 4.252, AUC: 0.818, AP: 0.785, Completeness: 0.380, Homogeneity: 0.365, NMI: 0.372
Epoch: 065, Loss: 4.226, AUC: 0.820, AP: 0.787, Completeness: 0.385, Homogeneity: 0.371, NMI: 0.377
Epoch: 066, Loss: 4.275, AUC: 0.820, AP: 0.788, Completeness: 0.387, Homogeneity: 0.374, NMI: 0.380
Epoch: 067, Loss: 4.269, AUC: 0.821, AP: 0.790, Completeness: 0.390, Homogeneity: 0.376, NMI: 0.383
Epoch: 068, Loss: 4.310, AUC: 0.820, AP: 0.790, Completeness: 0.383, Homogeneity: 0.382, NMI: 0.383
Epoch: 069, Loss: 4.292, AUC: 0.821, AP: 0.792, Completeness: 0.384, Homogeneity: 0.384, NMI: 0.384
Epoch: 070, Loss: 4.422, AUC: 0.822, AP: 0.793, Completeness: 0.379, Homogeneity: 0.379, NMI: 0.379
Epoch: 071, Loss: 4.369, AUC: 0.823, AP: 0.796, Completeness: 0.378, Homogeneity: 0.376, NMI: 0.377
Epoch: 072, Loss: 4.413, AUC: 0.825, AP: 0.798, Completeness: 0.375, Homogeneity: 0.375, NMI: 0.375
Epoch: 073, Loss: 4.492, AUC: 0.826, AP: 0.799, Completeness: 0.375, Homogeneity: 0.376, NMI: 0.375
Epoch: 074, Loss: 4.467, AUC: 0.827, AP: 0.800, Completeness: 0.372, Homogeneity: 0.373, NMI: 0.372
Epoch: 075, Loss: 4.516, AUC: 0.829, AP: 0.802, Completeness: 0.371, Homogeneity: 0.372, NMI: 0.371
Epoch: 076, Loss: 4.376, AUC: 0.830, AP: 0.803, Completeness: 0.370, Homogeneity: 0.371, NMI: 0.371
Epoch: 077, Loss: 4.471, AUC: 0.831, AP: 0.804, Completeness: 0.372, Homogeneity: 0.371, NMI: 0.372
Epoch: 078, Loss: 4.451, AUC: 0.832, AP: 0.806, Completeness: 0.369, Homogeneity: 0.356, NMI: 0.363
Epoch: 079, Loss: 4.486, AUC: 0.832, AP: 0.806, Completeness: 0.369, Homogeneity: 0.357, NMI: 0.363
Epoch: 080, Loss: 4.422, AUC: 0.833, AP: 0.807, Completeness: 0.373, Homogeneity: 0.364, NMI: 0.368
Epoch: 081, Loss: 4.376, AUC: 0.834, AP: 0.809, Completeness: 0.372, Homogeneity: 0.364, NMI: 0.368
Epoch: 082, Loss: 4.405, AUC: 0.835, AP: 0.810, Completeness: 0.371, Homogeneity: 0.366, NMI: 0.369
Epoch: 083, Loss: 4.523, AUC: 0.836, AP: 0.812, Completeness: 0.371, Homogeneity: 0.367, NMI: 0.369
Epoch: 084, Loss: 4.368, AUC: 0.838, AP: 0.813, Completeness: 0.371, Homogeneity: 0.369, NMI: 0.370
Epoch: 085, Loss: 4.401, AUC: 0.839, AP: 0.815, Completeness: 0.369, Homogeneity: 0.368, NMI: 0.368
Epoch: 086, Loss: 4.291, AUC: 0.841, AP: 0.816, Completeness: 0.373, Homogeneity: 0.372, NMI: 0.373
Epoch: 087, Loss: 4.317, AUC: 0.842, AP: 0.818, Completeness: 0.372, Homogeneity: 0.372, NMI: 0.372
Epoch: 088, Loss: 4.341, AUC: 0.844, AP: 0.819, Completeness: 0.382, Homogeneity: 0.380, NMI: 0.381
Epoch: 089, Loss: 4.195, AUC: 0.845, AP: 0.821, Completeness: 0.389, Homogeneity: 0.384, NMI: 0.386
Epoch: 090, Loss: 4.230, AUC: 0.847, AP: 0.824, Completeness: 0.386, Homogeneity: 0.386, NMI: 0.386
Epoch: 091, Loss: 4.210, AUC: 0.849, AP: 0.827, Completeness: 0.387, Homogeneity: 0.389, NMI: 0.388
Epoch: 092, Loss: 4.231, AUC: 0.851, AP: 0.830, Completeness: 0.417, Homogeneity: 0.400, NMI: 0.408
Epoch: 093, Loss: 4.092, AUC: 0.853, AP: 0.833, Completeness: 0.416, Homogeneity: 0.401, NMI: 0.409
Epoch: 094, Loss: 4.152, AUC: 0.855, AP: 0.836, Completeness: 0.418, Homogeneity: 0.404, NMI: 0.411
Epoch: 095, Loss: 4.162, AUC: 0.856, AP: 0.839, Completeness: 0.414, Homogeneity: 0.401, NMI: 0.407
Epoch: 096, Loss: 4.177, AUC: 0.857, AP: 0.842, Completeness: 0.416, Homogeneity: 0.403, NMI: 0.409
Epoch: 097, Loss: 4.186, AUC: 0.858, AP: 0.844, Completeness: 0.423, Homogeneity: 0.403, NMI: 0.413
Epoch: 098, Loss: 4.117, AUC: 0.859, AP: 0.846, Completeness: 0.413, Homogeneity: 0.401, NMI: 0.407
Epoch: 099, Loss: 4.163, AUC: 0.860, AP: 0.848, Completeness: 0.407, Homogeneity: 0.396, NMI: 0.401
Epoch: 100, Loss: 4.145, AUC: 0.861, AP: 0.850, Completeness: 0.455, Homogeneity: 0.431, NMI: 0.443
Epoch: 101, Loss: 4.151, AUC: 0.861, AP: 0.852, Completeness: 0.426, Homogeneity: 0.404, NMI: 0.415
Epoch: 102, Loss: 4.017, AUC: 0.862, AP: 0.853, Completeness: 0.428, Homogeneity: 0.406, NMI: 0.416
Epoch: 103, Loss: 4.206, AUC: 0.863, AP: 0.854, Completeness: 0.428, Homogeneity: 0.406, NMI: 0.417
Epoch: 104, Loss: 4.076, AUC: 0.863, AP: 0.854, Completeness: 0.427, Homogeneity: 0.406, NMI: 0.416
Epoch: 105, Loss: 4.116, AUC: 0.864, AP: 0.855, Completeness: 0.424, Homogeneity: 0.405, NMI: 0.414
Epoch: 106, Loss: 4.220, AUC: 0.864, AP: 0.855, Completeness: 0.425, Homogeneity: 0.405, NMI: 0.415
Epoch: 107, Loss: 4.047, AUC: 0.865, AP: 0.856, Completeness: 0.423, Homogeneity: 0.404, NMI: 0.413
Epoch: 108, Loss: 4.088, AUC: 0.865, AP: 0.856, Completeness: 0.421, Homogeneity: 0.403, NMI: 0.412
Epoch: 109, Loss: 3.981, AUC: 0.866, AP: 0.857, Completeness: 0.424, Homogeneity: 0.405, NMI: 0.414
Epoch: 110, Loss: 4.013, AUC: 0.866, AP: 0.857, Completeness: 0.439, Homogeneity: 0.425, NMI: 0.432
Epoch: 111, Loss: 4.023, AUC: 0.867, AP: 0.858, Completeness: 0.440, Homogeneity: 0.427, NMI: 0.434
Epoch: 112, Loss: 3.997, AUC: 0.867, AP: 0.859, Completeness: 0.442, Homogeneity: 0.428, NMI: 0.435
Epoch: 113, Loss: 3.985, AUC: 0.866, AP: 0.859, Completeness: 0.442, Homogeneity: 0.430, NMI: 0.436
Epoch: 114, Loss: 4.007, AUC: 0.866, AP: 0.859, Completeness: 0.443, Homogeneity: 0.430, NMI: 0.437
Epoch: 115, Loss: 3.966, AUC: 0.865, AP: 0.859, Completeness: 0.440, Homogeneity: 0.429, NMI: 0.435
Epoch: 116, Loss: 3.985, AUC: 0.865, AP: 0.859, Completeness: 0.415, Homogeneity: 0.413, NMI: 0.414
Epoch: 117, Loss: 3.918, AUC: 0.865, AP: 0.859, Completeness: 0.417, Homogeneity: 0.417, NMI: 0.417
Epoch: 118, Loss: 3.973, AUC: 0.865, AP: 0.859, Completeness: 0.415, Homogeneity: 0.415, NMI: 0.415
Epoch: 119, Loss: 3.948, AUC: 0.865, AP: 0.860, Completeness: 0.414, Homogeneity: 0.416, NMI: 0.415
Epoch: 120, Loss: 4.042, AUC: 0.866, AP: 0.860, Completeness: 0.415, Homogeneity: 0.417, NMI: 0.416
Epoch: 121, Loss: 3.988, AUC: 0.867, AP: 0.861, Completeness: 0.413, Homogeneity: 0.414, NMI: 0.414
Epoch: 122, Loss: 4.041, AUC: 0.868, AP: 0.862, Completeness: 0.430, Homogeneity: 0.446, NMI: 0.438
Epoch: 123, Loss: 3.951, AUC: 0.869, AP: 0.863, Completeness: 0.475, Homogeneity: 0.469, NMI: 0.472
Epoch: 124, Loss: 3.929, AUC: 0.870, AP: 0.864, Completeness: 0.432, Homogeneity: 0.447, NMI: 0.440
Epoch: 125, Loss: 4.038, AUC: 0.871, AP: 0.865, Completeness: 0.424, Homogeneity: 0.438, NMI: 0.431
Epoch: 126, Loss: 4.009, AUC: 0.872, AP: 0.866, Completeness: 0.421, Homogeneity: 0.436, NMI: 0.428
Epoch: 127, Loss: 3.995, AUC: 0.872, AP: 0.866, Completeness: 0.419, Homogeneity: 0.433, NMI: 0.426
Epoch: 128, Loss: 3.919, AUC: 0.873, AP: 0.867, Completeness: 0.419, Homogeneity: 0.433, NMI: 0.426
Epoch: 129, Loss: 3.976, AUC: 0.873, AP: 0.867, Completeness: 0.418, Homogeneity: 0.432, NMI: 0.425
Epoch: 130, Loss: 3.931, AUC: 0.873, AP: 0.867, Completeness: 0.420, Homogeneity: 0.435, NMI: 0.427
Epoch: 131, Loss: 3.960, AUC: 0.873, AP: 0.867, Completeness: 0.419, Homogeneity: 0.434, NMI: 0.426
Epoch: 132, Loss: 3.962, AUC: 0.873, AP: 0.867, Completeness: 0.421, Homogeneity: 0.436, NMI: 0.428
Epoch: 133, Loss: 3.912, AUC: 0.873, AP: 0.867, Completeness: 0.422, Homogeneity: 0.438, NMI: 0.430
Epoch: 134, Loss: 3.909, AUC: 0.874, AP: 0.868, Completeness: 0.418, Homogeneity: 0.434, NMI: 0.426
Epoch: 135, Loss: 3.923, AUC: 0.874, AP: 0.869, Completeness: 0.420, Homogeneity: 0.437, NMI: 0.429
Epoch: 136, Loss: 3.934, AUC: 0.875, AP: 0.871, Completeness: 0.416, Homogeneity: 0.434, NMI: 0.425
Epoch: 137, Loss: 3.905, AUC: 0.876, AP: 0.872, Completeness: 0.416, Homogeneity: 0.434, NMI: 0.425
Epoch: 138, Loss: 3.918, AUC: 0.877, AP: 0.872, Completeness: 0.415, Homogeneity: 0.434, NMI: 0.424
Epoch: 139, Loss: 3.895, AUC: 0.877, AP: 0.873, Completeness: 0.414, Homogeneity: 0.433, NMI: 0.423
Epoch: 140, Loss: 3.803, AUC: 0.878, AP: 0.873, Completeness: 0.474, Homogeneity: 0.482, NMI: 0.478
Epoch: 141, Loss: 3.831, AUC: 0.878, AP: 0.873, Completeness: 0.473, Homogeneity: 0.481, NMI: 0.477
Epoch: 142, Loss: 3.793, AUC: 0.878, AP: 0.873, Completeness: 0.476, Homogeneity: 0.484, NMI: 0.480
Epoch: 143, Loss: 3.879, AUC: 0.878, AP: 0.873, Completeness: 0.474, Homogeneity: 0.483, NMI: 0.479
Epoch: 144, Loss: 3.903, AUC: 0.878, AP: 0.873, Completeness: 0.443, Homogeneity: 0.451, NMI: 0.447
Epoch: 145, Loss: 3.879, AUC: 0.878, AP: 0.874, Completeness: 0.433, Homogeneity: 0.443, NMI: 0.438
Epoch: 146, Loss: 3.867, AUC: 0.878, AP: 0.875, Completeness: 0.438, Homogeneity: 0.447, NMI: 0.443
Epoch: 147, Loss: 3.907, AUC: 0.878, AP: 0.875, Completeness: 0.437, Homogeneity: 0.446, NMI: 0.441
Epoch: 148, Loss: 3.924, AUC: 0.878, AP: 0.876, Completeness: 0.436, Homogeneity: 0.446, NMI: 0.441
Epoch: 149, Loss: 3.835, AUC: 0.878, AP: 0.876, Completeness: 0.448, Homogeneity: 0.461, NMI: 0.455
Epoch: 150, Loss: 3.853, AUC: 0.878, AP: 0.876, Completeness: 0.449, Homogeneity: 0.461, NMI: 0.455
Traceback (most recent call last):
  File "argva_node_clustering.py", line 130, in <module>
    plot_points(test_data, colors)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "argva_node_clustering.py", line 121, in plot_points
    for i in range(dataset.num_classes):
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/data/in_memory_dataset.py", line 175, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no "
AttributeError: 'Planetoid' object has no attribute 'num_classes'
```
happens after the example finishes even when i install the latest pyg from source

`cd /opt/pyg; pip uninstall -y torch-geometric; rm -rf pytorch_geometric; git clone -b master https://github.com/pyg-team/pytorch_geometric.git; cd /opt/pyg/pytorch_geometric; python3 setup.py install; python3 examples/argva_node_clustering.py`

**Comment by puririshi98** [comment]
my PR now fixes the issue. the real underlying issue was in dataset, see changes @rusty1s

**Review by rusty1s — APPROVED** [review]

**Pull request merged**
